import os
import sys

if len(sys.argv) < 2:
    print('Must specify name of new page')
    quit()

name = (sys.argv[1]).lower()
filename = name.split('/')[-1]
folder_depth_string = "../" * len(name.split('/'))
newdir = os.path.join(os.path.dirname(__file__), name)

if os.path.exists(newdir):
    print(f'A page with name {name} already exists')
    quit()

print(f'creating new page with name {name}')

os.mkdir(newdir)

name_spaced = name.replace("_", " ").title()
keywords = "Catholics, United, Faith, " + name_spaced.replace(' ', ', ')

f = open(os.path.join(newdir, 'index.html'), 'w')
f.write('<!DOCTYPE html>\n')
f.write('<html lang="en">\n')
f.write('<head>\n')
f.write('  <meta charset="UTF-8">\n')
f.write('  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n')
f.write('  <meta name="description" content="">\n')
f.write(f'  <meta name="keywords" content="{keywords}">\n')
f.write('  <meta name="author" content="Daniel Gray">\n')
f.write(f'  <title>{name_spaced} | CUF</title>\n')
f.write(f'  <base href="{folder_depth_string}">\n')
f.write(f'  <script type="module" src="./{name}/{filename}_init.js"></script>\n')
f.write('  <script src="https://www.google.com/recaptcha/api.js"></script>\n')
f.write('</head>\n')
f.write('<body>\n')
f.write('  <cuf-header></cuf-header>\n')
f.write('  <div class="page-content">\n')
f.write('    <div class="actual-content">\n')
f.write(f'      <div class="test">{name.replace("_", " ").title()} content</div>\n')
f.write('    </div>\n')
f.write('    <cuf-sidebar panels=\'page\'></cuf-sidebar>\n')
f.write('  </div>\n')
f.write('  <cuf-footer-contact></cuf-footer-contact>\n')
f.write('</body>\n')
f.write('</html>')
f.close()

f = open(os.path.join(newdir, f'{filename}_init.js'), 'w')
f.write('// @ts-check\n')
f.write("'use strict';\n")
f.write('export {};\n')
f.write('\n')
f.write('const {version} = await import(`/scripts/version.js?v=${Date.now()}`);\n')
f.write('\n')
f.write("const stylesheet = document.createElement('link');\n")
f.write("stylesheet.setAttribute('rel', 'stylesheet');\n")
f.write("stylesheet.setAttribute('href', `/login/login.css?v=${version}`);\n")
f.write('document.head.appendChild(stylesheet);\n')
f.write('\n')
f.write("const logo = document.createElement('link');\n")
f.write("logo.setAttribute('rel', 'icon');\n")
f.write("logo.setAttribute('type', 'image/png');\n")
f.write("logo.setAttribute('href', `/__images/logo_square.png?v=${version}`);\n")
f.write('document.head.appendChild(logo);\n')
f.write('\n')
f.write(f'await import(`./{filename}.js?v=${{version}}`);\n')
f.write(f'await import(`/scripts/page_layout_components.js?v=${{version}}`);\n')
f.close()

f = open(os.path.join(newdir, f'{filename}.js'), 'w')
f.write('// @ts-check\n')
f.write("'use strict';\n")
f.close()

f = open(os.path.join(newdir, f'{filename}.css'), 'w')
f.write(f'@import "{folder_depth_string}styles.css";')
f.close()